### ISSUE TITLE
use base 64 token for loading images in Lightbox

### ISSUE THREAD

**Issue by farooq-asarstrategies** [themyth92/angular2-lightbox#11]
for (let i = 1; i <= 4; i++) {
      const src = 'demo/img/image' + i + '.jpg';
      const caption = 'Image ' + i + ' caption here';
      const thumb = 'demo/img/image' + i + '-thumb.jpg';
      const album = {
         src: src,
         caption: caption,
         thumb: thumb
};

this method is appending index at the end of file name. how can i use base 64 src for images?

**Comment by themyth92** [comment]
Hi, it does not support base64 image right now. Only image with url.

**Comment by themyth92** [comment]
You can use base64 with thumbnails but not with src.

**Comment by farooq-asarstrategies** [comment]
@themyth92  is there any way i can covert base64 image to Url ?

**Comment by themyth92** [comment]
Hi, can you just define base64 data in your src. For example:
```
const album = {
   src: 'data:image/gif;base64,R0lGODlhPQBEAPeoAJosM//AwO/Aw ...',
   caption: 'blabla'
}
```

**Comment by farooq-asarstrategies** [comment]
I am doing same. but i wont load images. even light box doesn't open.

**Comment by farooq-asarstrategies** [comment]
for (let i = 1; i <= 4; i++) {

const src = 'demo/img/image' + i + '.jpg';
const caption = 'Image ' + i + ' caption here';
const thumb = 'demo/img/image' + i + '-thumb.jpg';

}

how do i assign index to the base 64 images

**Comment by themyth92** [comment]
Hi, what is the value in your `this.galleries[albumb]['Attachments']` ?
It must have this format
```javascript
this.galleries[albumb]['Attachments'] = [
  {
    src: 'data:image/gif;base64...'
  },
  {
    src: 'data:image/gif;base64...'
  }
]
```

**Comment by farooq-asarstrategies** [comment]
@themyth92 i have other attributes also in 
this.galleries[albumb]['Attachments'] but src is there.

**Comment by themyth92** [comment]
I think you should change your implementations to 
```
for each gallery in result:
   result[gallery]['Attachments']['src'] = "data:" + filemime + ";base64," + file; // notice the removal of `attachment` attributes

// ...
this._lightbox.open(this.galleries[albumb]['Attachments'], image);
```

**Comment by farooq-asarstrategies** [comment]
@themyth92 i have similar implementation..each gallery has many attachments and for each attachment i do this 
result[gallery]['Attachments']["this is the attachment index"]['src'] = "data:" + filemime + ";base64," + file;

**Comment by themyth92** [comment]
Hmm, that's seem correct. Also on the second parameter is the index of the image right ?
Like
```
this._lightbox.open(this.galleries[albumb]['Attachments'], image);
// image is the index inside `this.galleries[albumb]['Attachments']` ?
```

**Comment by farooq-asarstrategies** [comment]
Yes. its the index of image.

**Comment by themyth92** [comment]
You mind post the result of `this.galleries[albumb]['Attachments']` here ? Can just mock the base64  data

**Comment by farooq-asarstrategies** [comment]
@themyth92   [https://ibb.co/eWyENa
](url)

**Comment by farooq-asarstrategies** [comment]
@themyth92  check this url now https://ibb.co/eWyENa

**Comment by themyth92** [comment]
Hi, can you just change `src` to point to some specific `url` and dont use base64 encode. I dont see any problems with your screenshot.
Try whether lighbox2 is shown up or not.

**Comment by themyth92** [comment]
And also can you check on your `html` do you attach the **click** event. E.g 
```html
<tag (click)="open(i)></tag>
```

**Comment by farooq-asarstrategies** [comment]
`<div class="col-container" *ngIf=" image.value['filemime'] ==  'image/jpeg' ">
                                                    <div class="image-trigger"  (click)="open(gallery.key,image.key)">
                                                          <div class="image-thumb">
                                                              <figure>
                                                                  <img [src] ="image.value['src']" alt="" height="200" width="200" />
                                                              </figure>
                                                          </div>
                                                          <div class="content-summary">
                                                              <h3>{{image.value['description']}}</h3>
                                                          </div>
                                                      </div>
                                                  </div>`

**Comment by farooq-asarstrategies** [comment]
<div class="col-container" *ngIf=" image.value['filemime'] ==  'image/jpeg' ">
  <div class="image-trigger"  (click)="open(gallery.key,image.key)">
        <div class="image-thumb">
            <figure>
                <img [src] ="image.value['src']" alt="" height="200" width="200" />
            </figure>
        </div>
        <div class="content-summary">
            <h3>{{image.value['description']}}</h3>
        </div>
    </div>
</div>

**Comment by themyth92** [comment]
If you change your src image some google images with url, is it work or not ?

**Comment by farooq-asarstrategies** [comment]
image modal not working for google images also. no error in console.

**Comment by farooq-asarstrategies** [comment]
@themyth92  it shows thumbnails for this. but no modal for images

**Comment by themyth92** [comment]
Hi, i am not sure what is going on on your side so I create a new [branch](https://github.com/themyth92/angular2-lightbox-webpack-demo/tree/feature/issue11) from my webpack demo. Can you see what's the difference here compare to your work.

The file you need to check is at **demo/app.component.ts** (notice the variables `this.galleries`)

You can clone on your end and run `npm install` -> `npm start` to start on your localhost. It is using one image with base64 encoded.

Tks.

**Comment by themyth92** [comment]
Closed, feel free to open if you have any problems !
