### ISSUE TITLE
ERROR TypeError: Cannot read property 'getComputedStyle' of undefined

### ISSUE THREAD

**Issue by prosenjit-itobuz** [themyth92/angular2-lightbox#13]
Hello,

After build `ng build --prod --env=prod --aot=true`

Lightbox not opening I get this error `ERROR TypeError: Cannot read property 'getComputedStyle' of undefined`

Have any idea what I missed.

`ng serve` Works fine.

**Info** 

```
@angular/cli: 1.0.6
node: 7.2.1
os: darwin x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.6
@angular/compiler-cli: 4.1.3
```

**Comment by themyth92** [comment]
Ok tks for reporting, I will give it a look !

**Comment by themyth92** [comment]
Hi should be fixed now. Please use the version 1.1.3 from npm. Tks :)

**Comment by prosenjit-itobuz** [comment]
Great work. No problem found in the production version.
