### ISSUE TITLE
Shadow portion of overlay does not expand when window is resized.  Works correctly in vanilla Lightbox2.

### ISSUE THREAD

**Issue by jasonburrows** [themyth92/angular2-lightbox#15]
Hi -

If you use this angular module, once the image loads in the lightbox, if you expand the window the shadow overlay moves to the right and does not expand to overlay the newly exposed portion of the window.  This problem does not happen in the 'real' Lightbox2 implementation.

You can see this using your own demo.

Navigate to your [demo](https://themyth92.com/project/angular2-lightbox/).  Click on an image to bring up the lightbox.  Expand the window horizontally.  You will see that the shaded overlay does not expand to fill the window.

Now navigate to the "real" lightbox2 implementation [here](http://lokeshdhakar.com/projects/lightbox2/).

Click on one of their sample images.  Expand the window horizontally.  You will see that the shadow overlay expands to take up the newly exposed screen real estate.

**Comment by themyth92** [comment]
Tks for reporting, I made some changes on CSS which differ from the original lightbox so there maybe some difference. I will give it a look.

**Comment by themyth92** [comment]
It has been fixed, please pull version [1.1.4](https://www.npmjs.com/package/angular2-lightbox) on npm

**Comment by jasonburrows** [comment]
Works great - thanks so much!
