### ISSUE TITLE
Because lightbox uses styles from node-modules/ folder, the styles don't get bundled into angular-cli production build

### ISSUE THREAD

**Issue by easy-one** [themyth92/angular2-lightbox#17]
Angular 2 production build produced by angular-cli implies that only bundled files from dist/ folder are placed to web server, not requiring node modules to be installed on production.

**Comment by themyth92** [comment]
So do you have any suggestions ?

**Comment by themyth92** [comment]
Hi, seems like you can add global styles to your `angular-cli.json` and it will get bundle with your build. See https://github.com/angular/angular-cli/wiki/stories-global-styles
```javascript
// angular-cli.json
{
   ...
   "styles": [
        "../node_modules/angular2-lightbox/lightbox.css",  // presume that your root at `./src`
        "styles.css"
    ],
    ...
}
```

**Comment by themyth92** [comment]
Close, feel free to open if you have any problems !
