### ISSUE TITLE
Error in production build : ERROR TypeError: Cannot read property 'getComputedStyle' of undefined

### ISSUE THREAD

**Issue by xoriuz** [themyth92/angular2-lightbox#19]
I'm using your module for my project, everything is working fine in development, but when I use it for production, there is an error when opening the lightbox:
`ERROR TypeError: Cannot read property 'getComputedStyle' of undefined`

I use angular CLI and for production build I run this command:
`ng build --prod`

After some checking, the error is in lightbox.component.ts file line 503
`return parseFloat(this._windowRef.getComputedStyle(elem.nativeElement, null).getPropertyValue(propertyName));`

It seems that the _windowRef is undefined for the production build. 

Could you help me with this issue?

Thanks in advance

**Comment by themyth92** [comment]
Hi, did you pull the latest version on npm.
This issue has been reported [here](https://github.com/themyth92/angular2-lightbox/issues/13) and  I have already pushed a fix since version 1.1.3

**Comment by xoriuz** [comment]
Hi there,

Updating to latest version works great!! 
You're the best 👍
