### ISSUE TITLE
Not working in IE

### ISSUE THREAD

**Issue by skype007** [themyth92/angular2-lightbox#20]
Hi,

I don't know if it's a known problem and if there's already a fix for that but if you tried to run the demo on Chrome : it works :D (the image is indeed displaying).
But in Internet Explorer, the image is not displaying :(

I'm working in a project with Angular4 FYI.

Best regards,
skype007

**Comment by themyth92** [comment]
Which IE version have you tried ?

**Comment by skype007** [comment]
I tried on IE11

**Comment by themyth92** [comment]
Ok tks, actually I have not tried using this with IE. Will give it a try and I will try to make it work on IE11 and above. Tks for reporting !

**Comment by skype007** [comment]
Alright thank you ;) For the time being, I'm using lightbox2 although I'd prefer your library because it's more "angular-friendly".
Thank you again for your work :)

**Comment by kanup** [comment]
I'm having the same issue. It breaks in lightbox.component.ts in _sizeContainer() method. The IE doesn't seem to support the transition. Therefore, _postResize() method doesn't get called at all. I don't know a good fix but my current work-around is to call _postResize method after a second or two using  setTimeout() to ensure it gets called in IE.

Do you guys have any thoughts?

**Comment by themyth92** [comment]
I guess the call back of those **transitionend** not being called for some reason. PR welcome if u know how to fix it.

**Comment by kanup** [comment]
Hi mate, I've sent the pull request. Apparently, it was some CSS properties for the transition and animation that caused this issue.

**Comment by themyth92** [comment]
Hi, tks for your help. Really appreciate it. Have you tested on IE 10 and 11, work fine ? Cuz I dont use windows.

**Comment by kanup** [comment]
I've tested it on IE 11 and it works fine. Although I haven't tested this in IE 10, animation-duration and transition-duration are said to be supported in IE 10.0 and above in w3schools. So, it should be fine.

**Comment by kanup** [comment]
@themyth92 Can you please create a new release (in npm)?
@skype007 Are you able to check the fix after the new release is made? Just so this issue can be closed.

**Comment by skype007** [comment]
Well if https://themyth92.com/project/angular2-lightbox/ is up to date, then I confirm it now works on IE11 ;) I think it can be closed (if it works on IE11, there's no reason it cannot work in IE10).

Good job ;-D
