### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by AleksandrukTad** [themyth92/angular2-lightbox#21]
Hi I have been trying to add Your lightbox to my website. I implemented everything, there are not errors but when i click img the page just increases its size. No other change. By increases its size i mean that i can scroll down to see page's background. 
I am still learning and dont know if I dont see obvious issues with my code or sth.
I am using newest version of Angular
https://github.com/AleksandrukTad/ganeshWeb

**Comment by AleksandrukTad** [comment]
Solved the problem. The issue was .angular-cli.json. Placing the css file link should happen there:
 "styles": [
        "styles.css",
        "../node_modules/angular2-lightbox/lightbox.css"
      ]

**Comment by themyth92** [comment]
Ok glad you solve the problem already. Happy coding :)
