### ISSUE TITLE
How to include in .angular-cli.json

### ISSUE THREAD

**Issue by heartmon** [themyth92/angular2-lightbox#22]
I have include the script in .angular-cli.json file: 
`
...
"scripts": [
        "../node_modules/angular2-lightbox/index.js"
      ],`

It works, however with an error 'Uncaught SyntaxError: Unexpected token export' in the browser console.
How should I use it correctly with .angular-cli.json?

**Comment by themyth92** [comment]
I dont think you need to put any content in `scripts` attribute. Just include lightbox directly in your module. [Demo](https://github.com/themyth92/angular2-lightbox-cli-demo)

**Comment by themyth92** [comment]
Closed. Feel free to open if u have any issues.
