### ISSUE TITLE
Center lightbox in window on open

### ISSUE THREAD

**Issue by d3rdud3** [themyth92/angular2-lightbox#23]
I was very glad about discovering this simple lightbox solution for angular2/4 application.

The only problem is, that in case of large page height, the lightbox is opened on the upper border of the page. 

Is there any way to center the lightbox on opening in the current view and prevent scrolling during the lightbox is opened ? Would be great if there would be a solution.

**Comment by themyth92** [comment]
I think it is pretty tough cuz you have different image with different height. If those images must be center in the page, it looks really weird during animation I think.

**Comment by d3rdud3** [comment]
The problem at the moment is that, on a page which has a scollbar, the lightbox is opened on top an the browser window, so it is on opening out of sight for the user. It would be great if it would open at least in the current view area. So I can spend a fixed height but its different with dynamic content.

**Comment by themyth92** [comment]
Ok i think Lightbox2 does have `disableScrolling` option. I will try to implement that. Is it ok ?

**Comment by themyth92** [comment]
Hello, the problem with lightbox out of view has been fixed. Please pull version 1.2.0 on npm.
Also I have added another options called **disabledScrolling** to not allow body to be scrolled when lightbox is opened.
Tks for reporting 👍

**Comment by lucaritossa** [comment]
@d3rdud3 with [v1.3.0](https://github.com/themyth92/angular2-lightbox/releases/tag/1.3.0) you have the new option **centerVertically** 😄
