### ISSUE TITLE
Can not use it for Angular 4

### ISSUE THREAD

**Issue by laoniustudio** [themyth92/angular2-lightbox#27]
Hi, I am using angular 4. there is no system.config.js I am using angular cli. light box is not work for me. any idea? thanks

**Comment by themyth92** [comment]
Could you please check console log if there is any Error ?

**Comment by themyth92** [comment]
You can take a look [here](https://github.com/themyth92/angular2-lightbox-cli-demo) for angular-cli example with angular2-lightbox

**Comment by laoniustudio** [comment]
thanks, i think i figure it out, thank you
