### ISSUE TITLE
lightbox-config.service.ts is not part of the compilation output. : Angular5 and angular-cli 1.5.0

### ISSUE THREAD

**Issue by Debananda** [themyth92/angular2-lightbox#30]
getting below error node_modules\angular2-lightbox\lightbox-config.service.ts is not part of the compilation output.

Environment:

"(at)angular/core": "^5.0.0",
"(at)angular/cli": "^1.5.0",
"angular2-lightbox": "^1.2.1",

**Comment by themyth92** [comment]
Tks for reporting. I will take a look ASAP

**Comment by themyth92** [comment]
Hello, there is an issue reported here https://github.com/angular/angular/issues/20091
What you can do is to put the `include` block to your `tsconfig.json`
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  },
  "include": [
    "node_modules/angular2-lightbox/index.ts"
  ]
}
```

**Comment by Debananda** [comment]
@themyth92 : the solution did not help me 

![image](https://user-images.githubusercontent.com/5937232/32380119-4f8ab5f0-c0d5-11e7-99d7-e8842cea845e.png)

**Comment by Debananda** [comment]
This is what worked for me 


{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  },
  "include": [
    "src/**/*",
    "node_modules/angular2-lightbox/*.service.ts",
    "node_modules/angular2-lightbox/*.component.ts",
    "node_modules/angular2-lightbox/*.module.ts"
  ]
}

**Comment by themyth92** [comment]
Hi there, could you give it a try ?
```json
{
    "compileOnSave": false,
    ...
  ],
  "lib": [
    "es2017",
    "dom"
  ]
  },
  "include": [
    "src/**/",
    "node_modules/angular2-lightbox/index.ts",
  ]
}
```

**Comment by Debananda** [comment]
@themyth92 : Yes its is working and is looking much better. but still it is an additional step to get it working.

**Comment by themyth92** [comment]
Hi @Debananda ,
Tks for clarification.

**Comment by miscoo1** [comment]
@Debananda solution not working for me.

Environment:
node v8.5.0
angular ^5.0.0
angular-cli ^1.5.4
angular2-lightbox: ^1.2.1

It throws me the same compilation error Module build failed ... desprite of included files in tsconfig.

**Comment by themyth92** [comment]
Hi there, can try with my [solution](https://github.com/themyth92/angular2-lightbox/issues/30#issuecomment-342032174) above ?

**Comment by dsuwirya** [comment]
This works for me:

  "include": [
    "src/**/*",
    "node_modules/angular2-lightbox/*.component.ts",
    "node_modules/angular2-lightbox/*.service.ts",
    "node_modules/angular2-lightbox/*.module.ts"
  ]

**Comment by alexrait** [comment]
It compiles now, but does not work.

**Comment by themyth92** [comment]
Should be ok with angular5 now !
