### ISSUE TITLE
Compile error when the null checks of the compiler are activated

### ISSUE THREAD

**Issue by stephanrauh** [themyth92/angular2-lightbox#34]
Line 75 of `lightbox.component.ts` tries to assign `null` to a number:

```typescript
@Input() currentImageIndex: number;
...
this.currentImageIndex = this.currentImageIndex || null;
```
I suggest replacing the `|| null` bit by `|| 0`. That compiles, and probably matches the intended behavior better: By default, the first image is shown. 

https://github.com/themyth92/angular2-lightbox/blob/325f9b855cf6469f3aa7d13821c69a15441a44e2/src/lightbox.component.ts#L75

**Comment by themyth92** [comment]
You want to submit a PR for this ?

**Comment by stephanrauh** [comment]
Oops - somehow I've missed your request for a PR. Thanks for fixing the bug yourself!
