### ISSUE TITLE
The source code with the node_modules folder is accidentially compiled

### ISSUE THREAD

**Issue by stephanrauh** [themyth92/angular2-lightbox#35]
The TypeScript source code of the library is compiled. IMHO, you can prevent this by packaging the NPM module a bit differently. The compiled JavaScript is part of the NPM package, so TypeScript and Angular should ignore the source code altogether.

My Angular CLI project doesn't have a system-config.json, so I didn't add the configuration as suggested. Maybe that's why the problem comes up in my project (but that's just a guess).

I'm not entirely sure, but I think [this blog](https://hackernoon.com/how-to-create-library-in-angular-2-and-publish-to-npm-from-scratch-f2b1272d6266) describes how to get rid of the TypeScript files (and how to put them in a dedicated folder ignored by the compiler).

**Comment by themyth92** [comment]
Ok tks. I will take a look into this 👍

**Comment by themyth92** [comment]
Should be ok for angular5 now !
