### ISSUE TITLE
Angular 5 can't import LightboxModule

### ISSUE THREAD

**Issue by viktorelo** [themyth92/angular2-lightbox#36]
Hi,

I've added the package to my project (installed via npm), but when I'm trying to import it in my app module it can't find the path of lightbox, hence I can't import it.

(at)angular/cli: "1.5.2"
(at)angular/core": "^5.0.2",
lightbox2: "^2.10.0",

**Comment by themyth92** [comment]
Hi there, what error do you receive ?

**Comment by viktorelo** [comment]
`./node_modules/angular2-lightbox/lightbox-config.service.ts
Module build failed: Error: [...]\node_modules\angular2-lightbox\lightbox-config.service.ts is not part of the compilation output.`

**Comment by themyth92** [comment]
Duplicate https://github.com/themyth92/angular2-lightbox/issues/30

**Comment by themyth92** [comment]
This should be fixed now !
