### ISSUE TITLE
Angular v5 integration

### ISSUE THREAD

**Issue by Aircliff** [themyth92/angular2-lightbox#38]
This is a great port. The only problem I had was around the documentation, if you follow it to integrate it into angular v5.* you will run into a couple of compile errors. So this isnt really a big issues if you know your way around angular 4+ but if you are newbie to angular and trying to use this port, you might run into some issues. So I suggest you update the documentation for angular 5+. Below is the config I used for angular 5.

In .angular-cli.json: add this line to the styles array "../node_modules/angular2-lightbox/lightbox.css"

then in tsconfig.json, I have this:

{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  },
  "include": [
    "src/**/*",
    "node_modules/angular2-lightbox/index.ts"
    ]
}

And then BAM, it worked like magic. Again this is a great port. Thank you sooooo much, was about to write my own version for angular, so you saved me a lot of time. Great job. thanks.

**Comment by themyth92** [comment]
Ah yeah, this issue has been reported here https://github.com/themyth92/angular2-lightbox/issues/30. But I will try to update the doc for angular 5.

**Comment by themyth92** [comment]
This should be fixed now !
