### ISSUE TITLE
angular2-lightbox found version 4, expected 3

### ISSUE THREAD

**Issue by SCLeonardoMedina** [themyth92/angular2-lightbox#42]
HI, please help me, I have this error but I can't resolve 

ERROR in Metadata version mismatch for module C:/Users/leoz3/Documents/ameixt2/node_modules/angular2-lightbox/index.d.ts, found version 4, expected 3, resolving symbol AppModule in C:/Users/leoz3/Documents/ameixt2/src/app/app.module.ts, resolving symbol AppModule in C:/Users/leoz3/Documents/ameixt2/src/app/app.module.ts

**Comment by themyth92** [comment]
Which lightbox version are u using as well as angular version ?

**Comment by casillas10** [comment]
I have met the similar problem for the "angular2-lightbox@1.2.2", 
but when I install "angular2-lightbox@1.2.1", the error disappeared.

My environments are 

```
Angular CLI: 1.6.5
Node: 9.3.0
OS: win32 x64
Angular: 4.4.6
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, tsc-wrapped

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.16
typescript: 2.3.4
webpack: 3.10.0
```

**Comment by themyth92** [comment]
Right tks, I will test again with angular4 👍
