### ISSUE TITLE
rxjs 6.0 issues and upgrade required asap

### ISSUE THREAD

**Issue by kushwahashiv** [themyth92/angular2-lightbox#57]
node_modules/angular2-lightbox/lightbox-event.service.d.ts(1,10): error TS2305: Module '"projects/node_modules/rxjs/Observable"' has no exported member 'Observable'.

**Comment by themyth92** [comment]
Please use rxjs v5 instead. I think it will break support angular v2 if I upgrade rxjs to v6.

**Comment by nharrer** [comment]
After having migrated everything in my project to rxjs 6 it would be a pain to go back to v5. We can however use rxjs-compat to satisfy angular2-lightbox until it has also switched to v6:

`npm i rxjs-compat --save`

**Comment by themyth92** [comment]
Ok cool tks. I think I will break support for angular2 from now on with the next upgrade.

**Comment by themyth92** [comment]
Hello, I just release a new project ngx-lightbox that will support angular >= 5x. Please use that instead. Tks.
