### ISSUE TITLE
Angular 6 error when in production mode

### ISSUE THREAD

**Issue by wahyuen** [themyth92/angular2-lightbox#58]
Version: 1.4.0

While upgrading to Angular 6 and rxjs6, it appears that lightbox is now having an issue but only when it has been compiled in production mode (ng serve --prod). This appears to work fine for me when in local mode and nothing is bundled/minified. (ng serve)

`main.f4370555954962b3bc67.js:1 ERROR TypeError: Cannot read property 'OPEN' of undefined
    at t.open (7.3518eb4674e91d353dfb.js:1)`

clicking on the trace in chrome debugger brings me to the section of code as:

`this._lightboxEvent.broadcastLightboxEvent(s.LIGHTBOX_EVENT.OPEN)`

**Comment by themyth92** [comment]
Ok cool. Tks for reporting. I will give it a look asap.

**Comment by themyth92** [comment]
Hello, I just release a new project [ngx-lightbox](https://github.com/themyth92/ngx-lightbox) that will support angular >= 5x. Please use that instead. Tks.
