### ISSUE TITLE
Angular 6 support

### ISSUE THREAD

**Issue by luisfpg** [themyth92/angular2-lightbox#59]
With the release of Angular 6, and, specially, RxJS 6, the imports for RxJS classes have changed, so now, for example, Observable should be imported from rxjs directly, and no longer from rxjs/Observable.
This issue is to request support for Angular 6.

**Comment by themyth92** [comment]
Hi there, I have changed to the project to https://github.com/themyth92/ngx-lightbox to support angular 5 and above. Thanks !

**Comment by themyth92** [comment]
Close for now !
