### ISSUE TITLE
Any of the _lightbox.open() method is not getting executed, though OPEN event is triggered.

### ISSUE THREAD

**Issue by bvsuryavanshi** [themyth92/angular2-lightbox#64]
open(index: number): void {
      // open lightbox
      // this._lightBox.open(this._album, index);
      // alert('clicked');
      // this._lightBox.open(this._album, index, { wrapAround: true, showImageNumberLabel: true,alwaysShowNavOnTouchDevices: true });
      this._subscription = this._lightboxEvent.lightboxEvent$.subscribe((event: IEvent) => this._onReceivedEvent(event));

    // override the default config
    this._lightBox.open(this._album, index, { wrapAround: true, showImageNumberLabel: true });
    
    }

**Comment by themyth92** [comment]
Sorry i dont get what you mean ?

**Comment by bvsuryavanshi** [comment]
I mean,

this._lightBox.open() method is not getting executed. On the click event ,open(index:number) gets called but actual lightbox does not open.

**Comment by themyth92** [comment]
Which angular version are u using ?

**Comment by themyth92** [comment]
Hi for angular 6, can u use this module instead. https://github.com/themyth92/ngx-lightbox

**Comment by themyth92** [comment]
This current `angular2-lightbox` only support 2 <= angular < 5

**Comment by themyth92** [comment]
You see any errors in the console ?

**Comment by bvsuryavanshi** [comment]
No any error on the console, created an alert on the Open event.
![Uploading Code.png…]()
![open event and console](https://user-images.githubusercontent.com/19649564/46078899-1cb91b00-c1b3-11e8-9c20-272e701e1876.png)

**Comment by themyth92** [comment]
Hmm i think there may be some css issue
Can you check if this piece of html is attached at the end of your page. Just check you Chrome `Elements` tab
<img width="878" alt="screenshot 2018-09-26 at 9 33 02 pm" src="https://user-images.githubusercontent.com/2434925/46083364-e0e27d80-c1d3-11e8-9222-d03c2732541d.png">

**Comment by themyth92** [comment]
Just trigger lightbox first and check your Chrome Developer Console

**Comment by themyth92** [comment]
Or do you input the lightbox css ?
If you use angular-cli:

Update your `angular.json`

```
{
  "styles": [
    "./node_modules/ngx-lightbox/lightbox.css",
    ...
  ],
}

**Comment by bvsuryavanshi** [comment]
It worked for me, there was the CSS issue, I did not include _"./node_modules/ngx-lightbox/lightbox.css"_, in angular.json 
Thank you so much for all your efforts to help me.
