### ISSUE TITLE
import { DOCUMENT } from '@angular/platform-browser';

### ISSUE THREAD

**Issue by madhuri09b** [themyth92/angular2-lightbox#66]
Hi,
I am having an issue with this import statements after updating with angular 8.
Any chances package will be updated soon?
As lightbox service using this import & in angular 8 we need to import it from angular/common.

**Comment by themyth92** [comment]
Please upgrade to v2.0.0 on npm. It has been released a week ago.
Also the package u should use is [ngx-lightbox](https://www.npmjs.com/package/ngx-lightbox)

**Comment by madhuri09b** [comment]
Thanks.
