### ISSUE TITLE
Not working in Angular4

### ISSUE THREAD

**Issue by sudheerec107** [themyth92/angular2-lightbox#7]
In angular4 cannot create service instance of Lightbox. it gives error Cannot find name 'Lightbox'. Eventhough it is imported
import {Lightbox}  from 'angular2-lightbox';

**Comment by themyth92** [comment]
Hi, do you have `system.config.js` configured ?
It should be like this
```javascript
{
  map: {
    'angular2-lightbox': 'node_modules/angular2-lightbox'
  },
  packages: {
    'angular2-lightbox': {
      main: './index.js',
      defaultExtension: 'js'
    }
  }
}
```

You can refer to my [demo](https://github.com/themyth92/angular2-lightbox/tree/master/demo) folder and [system.config.js](https://github.com/themyth92/angular2-lightbox/blob/master/systemjs.config.js), it is configured to use with angular4.
Hope it helps!

**Comment by sudheerec107** [comment]
I am using weback, what changes i should do?

**Comment by themyth92** [comment]
Hi, I have not used webpack for this project. Let me try it first and will give you the answer ASAP.

**Comment by themyth92** [comment]
Hi, I just create a [demo](https://github.com/themyth92/angular2-lightbox-webpack-demo). You can take a look !

**Comment by jasonburrows** [comment]
I have this working in Angular 4 with no complications.  You say you did:
`import {Lightbox} from 'angular2-lightbox';`

Did you also add it here:

`@NgModule({ imports:[LightboxModule]})` ?

**Comment by themyth92** [comment]
Yeah, you have to import it your module. [Readme](https://github.com/themyth92/angular2-lightbox#module)

**Comment by themyth92** [comment]
Closed. Feel free to open if u have any issues.

**Comment by Wasiq08** [comment]
@themyth92 how it can be used with angular-cli as its not working

**Comment by jasonburrows** [comment]
@Wasiq08 what specifically is the issue you are having - I have it working fine in angular-cli v1.2.6.

**Comment by themyth92** [comment]
You can take a look [here](https://github.com/themyth92/angular2-lightbox-cli-demo) for the angular cli demo.
