### ISSUE TITLE
ERROR in LightboxModule is not an NgModule

### ISSUE THREAD

**Issue by farooq-asarstrategies** [themyth92/angular2-lightbox#9]
When i start server it give me this error  "ERROR in LightboxModule is not an NgModule"
 it work fine after i make some changes and code recompiles

**Comment by themyth92** [comment]
Hi can i ask which changes you make ? And also do you use systemjs or webpack ?

**Comment by farooq-asarstrategies** [comment]
i am using webpack. no changes. just installed using npm

**Comment by themyth92** [comment]
So it is not working right ? If u use angular-cli ? Just to confirm so I can see what can I do ?

**Comment by farooq-asarstrategies** [comment]
i get this error  "ERROR in LightboxModule is not an NgModule" 
f after server starts. once i change any file (after recompiles) this error goes away and works ok.

**Comment by thecfguy** [comment]
lol.. I spent almost an hour due to this issue and surprisingly goes away on next compile as @farooq-asarstrategies  said.

**Comment by farooq-asarstrategies** [comment]
@themyth92 still facing the same issue. any possible fix for this ?

**Comment by themyth92** [comment]
Sorry I need to figure out what's wrong with angular-cli. There are some [issues](https://github.com/angular/angular-cli/issues/3426) about it online but I am not sure abt the solution yet.

**Comment by themyth92** [comment]
All PRs welcome

**Comment by themyth92** [comment]
Hi, please pull the latest version 1.1.2 on npm. Hopefully this problem can be fixed.

**Comment by farooq-asarstrategies** [comment]
@themyth92  Thanks . working perfect.

**Comment by themyth92** [comment]
Ok cool, close issue now :)
